name: fennac_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  get_it: ^9.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dartz: ^0.10.1

  auto_route: ^11.0.0

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.3
  hexcolor: ^3.0.1
  lottie: ^3.3.2

  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  video_player: ^2.10.1
  camera: ^0.11.2
  permission_handler: ^11.3.1
  geolocator: ^13.0.1

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  rename: ^3.1.0
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  auto_route_generator: ^10.4.0
  json_serializable: ^6.9.0
  freezed: ^3.0.0
  flutter_gen_runner: ^5.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/images/background/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/font/SF-Pro.ttf

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
